---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:   
  name: discovery
  namespace: default
  labels: 
      name: "discovery"
      keel.sh/policy: all
spec:
  replicas: 1
  template:
    metadata:
      name: discovery
      labels:
        app: discovery
    spec:
      containers:                    
        - image: gcr.io/storageos-public-service/discovery:0.1.14
          imagePullPolicy: Always 
          name: discovery
          command: ["/bin/discovery"]
          ports:
            - containerPort: 80
          env:                         
            - name: PORT
              value: "80"  
            - name: DATABASE_PATH
              value: /db  
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:          
          - name: cluster-db
            mountPath: /db
      # [START volumes]
      volumes:        
        - name: cluster-db
          gcePersistentDisk:
            # This disk must already exist. Check Readme
            pdName: cluster-db
            fsType: ext4        
      # [END volumes]                  
