apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    namespace: default
    labels:
      name: discovery      
    name: discovery
  spec:
    ports:    
    - name: api
      port: 8081
      protocol: TCP
      targetPort: 80
    selector:
      app: discovery
    sessionAffinity: None
    type: LoadBalancer
    # loadBalancerIP: 104.155.59.108

